import { describe, expect, test } from "bun:test";

import { formatEnvFile, parseEnvFile, pickEnv } from "../src/env-files.ts";

describe("env file helpers", () => {
  test("parseEnvFile reads dotenv-style key-values", () => {
    const env = parseEnvFile([
      "API_URL=http://localhost:3000",
      'TOKEN="quoted value"',
      "",
    ].join("\n"));

    expect(env).toEqual({
      API_URL: "http://localhost:3000",
      TOKEN: "quoted value",
    });
  });

  test("formatEnvFile writes sorted env values with headers and escaping", () => {
    const formatted = formatEnvFile(
      {
        TOKEN: 'abc"123',
        API_URL: "http://localhost:3000",
      },
      {
        header: ["# Generated by test"],
      }
    );

    expect(formatted).toBe([
      "# Generated by test",
      "",
      'API_URL="http://localhost:3000"',
      'TOKEN="abc\\"123"',
      "",
    ].join("\n"));
  });

  test("pickEnv returns only requested keys that exist", () => {
    expect(
      pickEnv(
        {
          API_URL: "http://localhost:3000",
          TOKEN: "secret",
        },
        ["TOKEN", "MISSING"]
      )
    ).toEqual({ TOKEN: "secret" });
  });
});
