import { defineManifest, pickEnv } from "@aureatus/keystone";

export default defineManifest({
  name: "smoke-workspace",
  sourceFiles: [".env.base", ".env.local"],
  initFiles: [
    {
      templatePath: ".env.example",
      destinationPath: ".env.base",
    },
  ],
  variables: {
    API_URL: {
      aliases: ["OLD_API_URL"],
      required: true,
    },
    ACCESS_TOKEN: {
      required: true,
      secret: true,
    },
    PORT: {
      defaultValue: "4300",
    },
    PUBLIC_API_URL: {
      defaultValue: (env) => env.API_URL,
    },
    APP_ORIGIN: {
      defaultValue: (env) => `http://127.0.0.1:${env.PORT ?? "4300"}`,
    },
  },
  build({ env }) {
    return {
      outputs: [
        {
          path: ".generated/server.env",
          env,
          header: [
            "# Generated by Keystone",
            "# Smoke test server output",
          ],
        },
        {
          path: ".generated/client.env",
          env: pickEnv(env, ["PUBLIC_APP_NAME", "PUBLIC_API_URL", "APP_ORIGIN"]),
          public: true,
          header: [
            "# Generated by Keystone",
            "# Smoke test client output",
          ],
        },
      ],
    };
  },
  doctor({ env }) {
    if (!env.PUBLIC_APP_NAME?.trim()) {
      return {
        errors: ["PUBLIC_APP_NAME must be present for smoke testing"],
      };
    }

    return { warnings: [], errors: [] };
  },
  clearPaths: [".generated/server.env", ".generated/client.env"],
});
