import { defineManifest, pickEnv } from "@aureatus/keystone";

export default defineManifest({
  name: "smoke-workspace",
  experimental: {
    serviceMap: true,
  },
  portless: {
    rootName: "smoke",
    proxyPort: 1355,
  },
  sourceFiles: [".env.base", ".env.local"],
  initFiles: [
    {
      templatePath: ".env.example",
      destinationPath: ".env.base",
    },
  ],
  variables: {
    API_URL: {
      aliases: ["OLD_API_URL"],
      required: true,
    },
    ACCESS_TOKEN: {
      required: true,
      secret: true,
    },
    PORT: {
      defaultValue: "4300",
    },
    PUBLIC_API_URL: {
      defaultValue: (env) => env.API_URL,
    },
    APP_ORIGIN: {
      defaultValue: (env) => env.APP_ORIGIN ?? `http://127.0.0.1:${env.PORT ?? "4300"}`,
    },
  },
  services: {
    api: {
      protocol: "http",
      runtime: "local-process",
      exposure: "portless",
      preferredPort: 4312,
      hostEnv: "API_HOST",
      portEnv: "API_PORT",
      urlEnv: "API_INTERNAL_URL",
      publicUrlEnv: "API_PUBLIC_URL",
      bindings: [{ env: "PUBLIC_API_URL", service: "api", from: "publicUrl" }],
    },
    web: {
      protocol: "http",
      runtime: "local-process",
      exposure: "portless",
      preferredPort: 4313,
      publicUrlEnv: "WEB_PUBLIC_URL",
      bindings: [{ env: "APP_ORIGIN", service: "web", from: "publicUrl" }],
    },
    postgres: {
      protocol: "postgres",
      runtime: "docker-network",
      serviceName: "postgres",
      connectPort: 5432,
      hostEnv: "PGHOST",
      portEnv: "PGPORT",
      urlEnv: "DATABASE_URL",
    },
  },
  build({ env }) {
    return {
      outputs: [
        {
          path: ".generated/server.env",
          env,
          header: [
            "# Generated by Keystone",
            "# Smoke test server output",
          ],
        },
        {
          path: ".generated/client.env",
          env: pickEnv(env, ["PUBLIC_APP_NAME", "PUBLIC_API_URL", "APP_ORIGIN", "WEB_PUBLIC_URL"]),
          public: true,
          header: [
            "# Generated by Keystone",
            "# Smoke test client output",
          ],
        },
      ],
    };
  },
  doctor({ env }) {
    if (!env.PUBLIC_APP_NAME?.trim()) {
      return {
        errors: ["PUBLIC_APP_NAME must be present for smoke testing"],
      };
    }

    return { warnings: [], errors: [] };
  },
  clearPaths: [".generated/server.env", ".generated/client.env"],
});
